// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfphoXrHxzY6tpslm_wXlmDzNJrj6Ys4',
    appId: '1:883560019350:web:f362c4670223d0a95719b7',
    messagingSenderId: '883560019350',
    projectId: 'mobdev-26dfb',
    authDomain: 'mobdev-26dfb.firebaseapp.com',
    storageBucket: 'mobdev-26dfb.appspot.com',
    measurementId: 'G-TRKPLK1Y3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGfH9WBLiplpGTwQ-bntcQ3hhdkOfqcg',
    appId: '1:883560019350:android:967d4bb87333b8c35719b7',
    messagingSenderId: '883560019350',
    projectId: 'mobdev-26dfb',
    storageBucket: 'mobdev-26dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4yXFMzWSVcw-mzcnb-RS7oddx69Y_rQ',
    appId: '1:883560019350:ios:cdfad8afc9471da45719b7',
    messagingSenderId: '883560019350',
    projectId: 'mobdev-26dfb',
    storageBucket: 'mobdev-26dfb.appspot.com',
    iosBundleId: 'com.example.dt917628579A1F24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4yXFMzWSVcw-mzcnb-RS7oddx69Y_rQ',
    appId: '1:883560019350:ios:cdfad8afc9471da45719b7',
    messagingSenderId: '883560019350',
    projectId: 'mobdev-26dfb',
    storageBucket: 'mobdev-26dfb.appspot.com',
    iosBundleId: 'com.example.dt917628579A1F24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtfphoXrHxzY6tpslm_wXlmDzNJrj6Ys4',
    appId: '1:883560019350:web:33c2a6b6f39f7ade5719b7',
    messagingSenderId: '883560019350',
    projectId: 'mobdev-26dfb',
    authDomain: 'mobdev-26dfb.firebaseapp.com',
    storageBucket: 'mobdev-26dfb.appspot.com',
    measurementId: 'G-WK4X4E47J6',
  );
}
